const CANDIDATES = [
  { id: "c01", name: "王俊凯", image: "assets/members/c01.webp" },
  { id: "c02", name: "王源", image: "assets/members/c02.webp" },
  { id: "c03", name: "易烊千玺", image: "assets/members/c03.webp" },
  { id: "c04", name: "马嘉祺", image: "assets/members/c04.webp" },
  { id: "c05", name: "丁程鑫", image: "assets/members/c05.webp" },
  { id: "c06", name: "宋亚轩", image: "assets/members/c06.webp" },
  { id: "c07", name: "刘耀文", image: "assets/members/c07.webp" },
  { id: "c08", name: "张真源", image: "assets/members/c08.webp" },
  { id: "c09", name: "严浩翔", image: "assets/members/c09.webp" },
  { id: "c10", name: "贺峻霖", image: "assets/members/c10.webp" },
  { id: "c11", name: "朱志鑫", image: "assets/members/c11.webp" },
  { id: "c12", name: "张泽禹", image: "assets/members/c12.webp" },
  { id: "c13", name: "张极", image: "assets/members/c13.webp" },
  { id: "c14", name: "左航", image: "assets/members/c14.webp" },
  { id: "c15", name: "苏新皓", image: "assets/members/c15.webp" },
  { id: "c16", name: "童禹坤", image: "assets/members/c16.webp" },
  { id: "c17", name: "邓佳鑫", image: "assets/members/c17.webp" },
  { id: "c18", name: "穆祉丞", image: "assets/members/c18.webp" },
  { id: "c19", name: "张子墨", image: "assets/members/c19.webp" },
  { id: "c20", name: "黄朔", image: "assets/members/c20.webp" },
  { id: "c21", name: "张峻豪", image: "assets/members/c21.webp" },
  { id: "c22", name: "余宇涵", image: "assets/members/c22.webp" },
  { id: "c23", name: "官俊臣", image: "assets/members/c23.webp" },
  { id: "c24", name: "张桂源", image: "assets/members/c24.webp" },
  { id: "c25", name: "张函瑞", image: "assets/members/c25.webp" },
  { id: "c26", name: "王橹杰", image: "assets/members/c26.webp" },
  { id: "c27", name: "王烁然", image: "assets/members/c27.webp" },
  { id: "c28", name: "左奇函", image: "assets/members/c28.webp" },
  { id: "c29", name: "陈奕恒", image: "assets/members/c29.webp" },
  { id: "c30", name: "杨博文", image: "assets/members/c30.webp" },
  { id: "c31", name: "杨涵博", image: "assets/members/c31.webp" },
  { id: "c32", name: "张奕然", image: "assets/members/c32.webp" },
  { id: "c33", name: "聂玮辰", image: "assets/members/c33.webp" },
  { id: "c34", name: "陈思罕", image: "assets/members/c34.webp" },
  { id: "c35", name: "魏子宸", image: "assets/members/c35.webp" },
  { id: "c36", name: "李煜东", image: "assets/members/c36.webp" },
  { id: "c37", name: "陈浚铭", image: "assets/members/c37.webp" },
  { id: "c38", name: "吕政熙", image: "assets/members/c38.webp" },
  { id: "c39", name: "杨云皓", image: "assets/members/c39.webp" },
  { id: "c40", name: "侯王子", image: "assets/members/c40.webp" },
  { id: "c41", name: "刘禹辰", image: "assets/members/c41.webp" },
  { id: "c42", name: "俞政霖", image: "assets/members/c42.webp" },
  { id: "c43", name: "高铭阳", image: "assets/members/c43.webp" },
  { id: "c44", name: "杨子豪", image: "assets/members/c44.webp" },
  { id: "c45", name: "宋金泽", image: "assets/members/c45.webp" },
  { id: "c46", name: "任玄哲", image: "assets/members/c46.webp" },
  { id: "c47", name: "皮子渝", image: "assets/members/c47.webp" },
  { id: "c48", name: "智恩涵", image: "assets/members/c48.webp" },
  { id: "c49", name: "沈子航", image: "assets/members/c49.webp" },
  { id: "c50", name: "杨林好", image: "assets/members/c50.webp" },
  { id: "c51", name: "朱映宸", image: "assets/members/c51.webp" },
  { id: "c52", name: "张誉严", image: "assets/members/c52.webp" },
  { id: "c53", name: "陈璟翊", image: "assets/members/c53.webp" },
  { id: "c54", name: "胡阿米", image: "assets/members/c54.webp" },
  { id: "c55", name: "魏新航", image: "assets/members/c55.webp" },
  { id: "c56", name: "佟戈", image: "assets/members/c56.webp" },
  { id: "c57", name: "赵俊羽", image: "assets/members/c57.webp" },
  { id: "c58", name: "刘瀚辰", image: "assets/members/c58.webp" },
  { id: "c59", name: "陈燊", image: "assets/members/c59.webp" },
  { id: "c60", name: "越艺晨", image: "assets/members/c60.webp" }
];

const POSITIONS = [
  { key: "leader", label: "队长", hint: "最多 1 人", min:0, max:1 },
  { key: "center", label: "C位", hint: "最多 1 人", min:0, max:1 },
  { key: "vocal", label: "主唱", hint: "最多 3 人", min:0, max:3 },
  { key: "dance", label: "主舞", hint: "最多 3 人", min:0, max:3 },
  { key: "rap", label: "Rap", hint: "最多 3 人", min:0, max:3 },
  { key: "visual", label: "门面", hint: "最多 3 人", min:0, max:3 },
  { key: "ace", label: "ACE", hint: "最多 3 人", min:0, max:3 }
];